// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vjgxxnohufnirignokjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZ3h4bm9odWZuaXJpZ25va2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMDAwNDUsImV4cCI6MjA4OTg3NjA0NX0.KvDnUnULPoSJGuO7tnpOK3X2MlmfAqcY6GB7TS0RMEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);